# Generated by Django 3.2.8 on 2021-10-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioTransribe',
            new_name='AudioTranscribe',
        ),
    ]
