# Generated by Django 3.2.8 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_audiotransribe_audiotranscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='audiofiles', verbose_name='Аудиофайл')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioTranscribe',
        ),
    ]
